kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  annotations:
    "volume.beta.kubernetes.io/storage-class": "gold"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
