apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
     ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
