apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx-v1
spec:
#  replicas: 2
  selector:
    app: nginx
    version: v1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.8
        ports:
        - containerPort: 80
#      restartPolicy: Never
